server:
  port: 8080

zk:
  config:
    connectionString: 39.108.65.230:2181


xin:
  awell:
    dt:
      app-name: dt-server
      app-id: 4d2e166d-82ad-49d0-b3d1-88f22eb13494
      enable: true


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: xin.awell.dt.server.domain
  type-handlers-package: xin.awell.dt.server.utils.typeHandler



spring:
  datasource:
    druid:
      username: lzp
      url: jdbc:mysql://39.108.65.230:3306/dt
      password: chuyin12345

